import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // shadcn/ui tokens — updated to match new palette via CSS vars
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Design system tokens
        "surface":                  "#f8f9fa",
        "surface-bright":           "#f8f9fa",
        "surface-dim":              "#d9dadb",
        "surface-variant":          "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f3f4f5",
        "surface-container":        "#edeeef",
        "surface-container-high":   "#e7e8e9",
        "surface-container-highest":"#e1e3e4",
        "on-surface":               "#191c1d",
        "on-surface-variant":       "#43474a",
        "on-primary":               "#ffffff",
        "on-primary-container":     "#99a9b2",
        "on-primary-fixed":         "#0e1d25",
        "on-primary-fixed-variant": "#3a4951",
        "on-secondary":             "#ffffff",
        "on-secondary-container":   "#785e3e",
        "on-background":            "#191c1d",
        "on-tertiary":              "#ffffff",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
        "primary-container":        "#2f3e46",
        "primary-fixed":            "#d5e5ef",
        "primary-fixed-dim":        "#b9c9d3",
        "secondary-container":      "#fddab2",
        "secondary-fixed":          "#ffddb6",
        "secondary-fixed-dim":      "#e2c19b",
        "tertiary":                 "#2e2512",
        "tertiary-container":       "#453b26",
        "tertiary-fixed":           "#f1e0c3",
        "tertiary-fixed-dim":       "#d5c5a9",
        "on-tertiary-container":    "#b4a58a",
        "on-tertiary-fixed":        "#231a08",
        "on-tertiary-fixed-variant":"#504530",
        "outline":                  "#73787b",
        "outline-variant":          "#c3c7ca",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "surface-tint":             "#516169",
        "inverse-primary":          "#b9c9d3",
        "inverse-surface":          "#2e3132",
        "inverse-on-surface":       "#f0f1f2",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        "card": "0 8px 24px rgba(25, 40, 48, 0.05)",
        "card-lg": "0 16px 40px rgba(25, 40, 48, 0.08)",
        "top": "0 -4px 24px rgba(25, 40, 48, 0.06)",
        "bottom": "0 4px 24px rgba(25, 40, 48, 0.06)",
      },
    },
  },
  plugins: [],
}
export default config
